"""Atomic permissions (RBAC) for the platform authorization policy."""
from __future__ import annotations

from enum import StrEnum


class Permission(StrEnum):
    SCENARIO_READ_PUBLIC = "scenario_read_public"
    SCENARIO_EVALUATE_PUBLISHED = "scenario_evaluate_published"
    EVALUATION_MODERATE = "evaluation_moderate"
    SCENARIO_CREATE_DRAFT = "scenario_create_draft"
    SCENARIO_READ_OWN = "scenario_read_own"
    SCENARIO_UPDATE_OWN = "scenario_update_own"
    SCENARIO_DELETE_OWN = "scenario_delete_own"
    SCENARIO_SUBMIT_REVIEW = "scenario_submit_review"
    SCENARIO_READ_REVIEW_QUEUE = "scenario_read_review_queue"
    SCENARIO_UPDATE_IN_REVIEW = "scenario_update_in_review"
    SCENARIO_START_REVIEW = "scenario_start_review"
    SCENARIO_REQUEST_CHANGES = "scenario_request_changes"
    SCENARIO_MARK_NOT_SUITABLE = "scenario_mark_not_suitable"
    SCENARIO_REOPEN_NOT_SUITABLE = "scenario_reopen_not_suitable"
    SCENARIO_PUBLISH = "scenario_publish"
    SCENARIO_SUGGESTION_CREATE = "scenario_suggestion_create"
    SCENARIO_SUGGESTION_READ = "scenario_suggestion_read"
    USER_READ_SELF = "user_read_self"
    USER_UPDATE_SELF = "user_update_self"
    USER_CHANGE_OWN_PASSWORD = "user_change_own_password"
    USER_ADMIN_CREATE_INVESTIGATOR = "user_admin_create_investigator"
    USER_ADMIN_SET_USER_ROLE = "user_admin_set_user_role"
    USER_ADMIN_SET_ACCOUNT_STATUS = "user_admin_set_account_status"
    USER_ADMIN_READ_ANY_PROFILE = "user_admin_read_any_profile"
    USER_ADMIN_UPDATE_ANY_PROFILE = "user_admin_update_any_profile"
    USER_ADMIN_MANAGE_REVIEWER_ASSIGNMENTS = "user_admin_manage_reviewer_assignments"
    USER_ADMIN_MANAGE_SCENARIO_CLASSIFICATION = "user_admin_manage_scenario_classification"
    USER_ADMIN_MANAGE_ETHICAL_RISK_CATALOG = "user_admin_manage_ethical_risk_catalog"
    AUDIT_EVENT_CREATE = "audit_event_create"
    AUDIT_EVENT_READ = "audit_event_read"
